name: 'Init environment'
description: 'Install dependencies'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Set up Node 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install Dependencies
      run: npm ci
      shell: bash
