name: Checks
on:
  push:
    branches:
      - master
      - release
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  lint:
    name: Lint
    runs-on: arc-runners-small
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Display Node.js version
        run: node --version

      - name: Lint
        run: npm run lint

  type-check:
    name: Type Check
    runs-on: arc-runners-small
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Display Node.js version
        run: node --version

      - name: Type Check
        run: npm run type-check

  tests:
    name: Tests on ${{ matrix.node-version }}
    runs-on: arc-runners-small
    env:
      NODE_ENV: test_lib
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 18.x, 20.x, 21.x, 22.x ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - uses: browser-actions/setup-chrome@latest

      - name: Display Chrome version
        run: chrome --version

      - name: Display Node.js version
        run: node --version

      - name: Run tests
        run: npm run test
