name: Checks
on: [ push ]

jobs:
  Node_14:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/node14
      - run: chrome --version
      - name: node version
        run: node --version
      - name: test
        run: npm test
  Node_16:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/node16
      - run: chrome --version
      - name: node version
        run: node --version
      - name: test
        run: npm test
  Node_18:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/node18
      - run: chrome --version
      - name: node version
        run: node --version
      - name: test
        run: npm test
